# Generated by Django 2.2 on 2021-10-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_brand_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='prefix',
            field=models.CharField(default='mol', max_length=3),
            preserve_default=False,
        ),
    ]
