# Generated by Django 2.2 on 2021-10-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_brand_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
