# Generated by Django 2.2 on 2021-10-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_brand_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='page',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
