# Generated by Django 2.2 on 2022-02-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20220131_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='cookie',
            field=models.TextField(blank=True, null=True),
        ),
    ]
