# Generated by Django 2.2 on 2022-02-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_process_cookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('n', 'None'), ('x', 'En proceso'), ('s', 'Exitoso'), ('f', 'Error')], default='n', max_length=1),
        ),
    ]
