# Generated by Django 2.2 on 2022-02-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_process_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='started',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
