# Generated by Django 2.2 on 2022-02-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_auto_20220203_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='started',
            field=models.DateTimeField(),
        ),
    ]
