# Generated by Django 2.2 on 2021-10-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='des'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
