# Generated by Django 2.2 on 2021-11-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='national',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
