# Generated by Django 2.2 on 2021-12-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_product_id_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trend',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
