# Generated by Django 2.2 on 2022-02-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20220131_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta',
            field=models.TextField(default='{}', editable=False),
        ),
    ]
